package main

var VTEX_FLAG_CUBE_TEXTURE = 0x10



var VTEX_FORMAT_DXT1 = 0x01
var VTEX_FORMAT_DXT5 = 0x02
var VTEX_FORMAT_R8 = 0x03
var VTEX_FORMAT_R8G8B8A8_UINT = 0x04
var VTEX_FORMAT_PNG_R8G8B8A8_UINT = 0x10
var VTEX_FORMAT_PNG_PNG_DXT5 = 0x12
var VTEX_FORMAT_BC7 = 0x14
var VTEX_FORMAT_BC4 = 0x1B
var VTEX_FORMAT_BGRA8888 = 0x1C


const VTEX_EXTRA_DATA_TYPE_UNKNOWN = 0;
const VTEX_EXTRA_DATA_TYPE_FALLBACK_BITS = 1;
const VTEX_EXTRA_DATA_TYPE_SHEET = 2;
const VTEX_EXTRA_DATA_TYPE_FILL_TO_POWER_OF_TWO = 3;
const VTEX_EXTRA_DATA_TYPE_COMPRESSED_MIP_SIZE = 4;
